version: "3"
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      DATA_DIR: /tmp/localstack/data
      USE_LIGHT_IMAGE: "true"
      HOST_TMP_FOLDER: .localstack
      PROCESS_LIST_FILES_BUCKET: direct-upload
    volumes:
      - localstack-data:/tmp/localstack/data

volumes:
  localstack-data:
