version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "knockme-observation"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rf1jztk65zmj"
s3_prefix = "knockme-observation"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
