version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tasuki-observer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-oj0ivg2a8u8p"
s3_prefix = "tasuki-observer"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SourceLogGroupStaging=\"/ecs/tasuki-land-staging\" SourceLogGroup=\"/ecs/tasuki-land\""
