AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Tasuki Observer

Globals:
  Function:
    Timeout: 3

Parameters:
  SourceLogGroup:
    Type: "String"
    Default: "/ecs/tasuki-land-staging"

Resources:
  TasukiObserverFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/tasuki_observer/
      Timeout: 60
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          EMAIL_SNS_TOPIC_ARN: !Ref TasukiEmailTopic
      Policies:
        - CloudWatchLogsReadOnlyAccess
        - AmazonSNSFullAccess

  TasukiObserverLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${TasukiObserverFunction}
      RetentionInDays: 14

  TasukiEmailTopic:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: TasukiEmailTopic

  TasukiEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: nakamura.masakatsu@gmail.com
      Protocol: email
      TopicArn: !Ref TasukiEmailTopic

  TasukiLandStagingSubscriptionFilter:
    DependsOn:
      - LambdaInvokePermission
    Type: "AWS::Logs::SubscriptionFilter"
    Properties:
      LogGroupName: !Ref SourceLogGroup
      FilterPattern: |
        [str = "/*" || str = "*ERROR*" || str = "*WARN"]
      DestinationArn: !GetAtt TasukiObserverFunction.Arn

  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !Ref TasukiObserverFunction
      Action: "lambda:InvokeFunction"
      Principal: !Sub "logs.amazonaws.com"
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${SourceLogGroup}:*"

Outputs:
  TasukiObserver:
    Description: "Tasuki Observer Lambda Function ARN"
    Value: !GetAtt TasukiObserverFunction.Arn
